### ISSUE TITLE
sourceIP and sensorID get parsed wrong when using a "-" in sensor name

### ISSUE THREAD

**Issue by tweemeterjop** [shiva-spampot/shiva#10]
If you're using a "-" sign in your sensor name the sourceIP and sensorID get parsed wrong. The shivamailparser.py in shiva/analyzer/core/shivamailparser.py is parsing the filename of the spam files from the queue. Now if your sensor name includes a "-", the parser will read parts of the sensor name as sourceIP.

Spam file with sensor name containing a "-".
`1422100645.M500540P912Q2-127.0.0.1-my-shiva-sensor`

Code snippet from shivamailparser.py:
```python
mailFields['sourceIP'] = key.split("-")[-2]
mailFields['sensorID'] = key.split("-")[-1]
```
Which leaves you with `sourceIP=shiva` and `sensorID=sensor`.

**Comment by b0nd** [comment]
Thanks!
Yes, you are right and you've highlighted the correct code lines. 

But that has been picked up as a loose standard for extracting information from file name itself. Infact, another field is ready to be inserted in file name the same way and at the moment we are sticking to this loose standard only.
We'll update the same in read-me.
