### ISSUE TITLE
How to test the working of Shiva Honeypot?

### ISSUE THREAD

**Issue by Waseem-farooqui** [shiva-spampot/shiva#14]
I have deploy Shiva honeypot for research on my Virtual System.
I want to test it, will you please share me any link that will help me in testing this honeypot.
By test I mean on which email address I can send/receive spams.
I also want to know the structure of receiver, Is it receive spam on single email address say `shiva.honey@gmail.com`. 
If I am not right please correct me.

**Comment by b0nd** [comment]
Any email id could be used. 
For testing, either you could use some mail client script (python) or a proper email client. Just mention the IP & port of shiva sensor for smtp settings and you are good to go.

**Comment by Waseem-farooqui** [comment]
How can we define email ids.
Like want to receive only those email which have email ids defined in some configurations.

**Comment by RahulBinjve** [comment]
Hi @Waseem-farooqui,

SHIVA is designed to be an open relay spam honeypot, and not being a spam trap. As in a spam trap you create an email address to catch the spam. In SHIVA, you setup an open relay SMTP server to which spammers can connect and send the spam. So, to test your setup, you can start the receiver and analyzer and try sending the mail via SHIVA's SMTP server. In Python, it can be achieved by a script similar to this - http://www.tutorialspoint.com/python/python_sending_email.htm. Just be sure to change SMTP host and port values.

Let us know if this answers your query.

Thank you.

**Comment by Waseem-farooqui** [comment]
Thanks @RahulBinjve
Thank you that's the answer I was requiring.

**Comment by RahulBinjve** [comment]
Closing issue as the question has been answered.
