### ISSUE TITLE
How can we differentiate spam email with ham.

### ISSUE THREAD

**Issue by Waseem-farooqui** [shiva-spampot/shiva#16]
I tested shiva by sending spam and ham email, it is logging both.
Is there any extension through which we can distinguish between normal email(ham) and spam email.
Like our emailing servers (e.g gmail) can automatically send spamming mail spam box.

**Comment by b0nd** [comment]
No, it hasn't been coded that way. Based on practicality that spammers are the consumers of open-relay or hacked SMTP servers, no attempt has been made to distinguish between spam/legit mail.
But yes, a thought could be put in to design a logic that could further categories spams (e.g. next-to-kin, phishing, advertisement etc.)
