### ISSUE TITLE
ImportError: No module name docutils.core

### ISSUE THREAD

**Issue by zerokewl88** [shiva-spampot/shiva#8]
Tried installing using ./install and when installing Lamson (receiver) and creating project:

gets to Running setup.py egg_info for package python-daemon and throws a error... 

File "version.py", line 51, in <module>
import docutils.core

ImportError: No module name docutils.core

I have added and isntalled python-docutils, and also pip install docutils, but its still not working ?

however, when i installed this a few days ago on another vm and it worked fine? has something changed ? or am i doing something wrong ? thank you.

**Comment by RahulBinjve** [comment]
Hi zerokewl88,

Are you facing this problem when you try to run Receiver or while installing SHIVA itself? This error is definitely new to me.

**Comment by zerokewl88** [comment]
Hi Rahul, 

I am trying to install it.

Here is a complete trace of the terminal output.

[*] Setting up SHIVA Receiver!

[*] Creating Virtual Environment: 
New python executable in shivaReceiver/bin/python
Installing distribute.............................................................................................................................................................................................done.
Installing pip...............done.

[*] Installing Lamson (receiver) and creating project: 
Downloading/unpacking lamson==1.3.4
  Downloading lamson-1.3.4.tar.gz (695Kb): 695Kb downloaded
  Running setup.py egg_info for package lamson
    
    warning: no files found matching 'README'
Downloading/unpacking chardet (from lamson==1.3.4)
  Downloading chardet-2.3.0.tar.gz (164Kb): 164Kb downloaded
  Running setup.py egg_info for package chardet
    
    warning: no files found matching 'COPYING'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.gif' under directory 'docs'
Downloading/unpacking jinja2 (from lamson==1.3.4)
  Downloading Jinja2-2.7.3.tar.gz (378Kb): 378Kb downloaded
  Running setup.py egg_info for package jinja2
    
    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking mock (from lamson==1.3.4)
  Downloading mock-1.0.1.tar.gz (818Kb): 818Kb downloaded
  Running setup.py egg_info for package mock
    
    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
Downloading/unpacking nose (from lamson==1.3.4)
  Downloading nose-1.3.4.tar.gz (277Kb): 277Kb downloaded
  Running setup.py egg_info for package nose
    
    no previously-included directories found matching 'doc/.build'
Downloading/unpacking python-daemon (from lamson==1.3.4)
  Downloading python-daemon-2.0.1.tar.gz (62Kb): 62Kb downloaded
  Running setup.py egg_info for package python-daemon
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/honeydrive/Desktop/shiva-installer/shiva/shivaReceiver/build/python-daemon/setup.py", line 27, in <module>
        import version
      File "version.py", line 51, in <module>
        import docutils.core
    ImportError: No module named docutils.core
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/honeydrive/Desktop/shiva-installer/shiva/shivaReceiver/build/python-daemon/setup.py", line 27, in <module>

    import version

  File "version.py", line 51, in <module>

    import docutils.core

ImportError: No module named docutils.core

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/honeydrive/Desktop/shiva-installer/shiva/shivaReceiver/build/python-daemon
Storing complete log in /home/honeydrive/.pip/pip.log
Traceback (most recent call last):
  File "/home/honeydrive/Desktop/shiva-installer/shiva/shivaReceiver/bin/pip", line 9, in <module>
    load_entry_point('pip==1.1', 'console_scripts', 'pip')()
  File "/home/honeydrive/Desktop/shiva-installer/shiva/shivaReceiver/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/__init__.py", line 116, in main
    return command.main(args[1:], options)
  File "/home/honeydrive/Desktop/shiva-installer/shiva/shivaReceiver/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 141, in main
    log_fp = open_logfile(log_fn, 'w')
  File "/home/honeydrive/Desktop/shiva-installer/shiva/shivaReceiver/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 168, in open_logfile
    log_fp = open(filename, mode)
IOError: [Errno 13] Permission denied: '/home/honeydrive/.pip/pip.log'
honeydrive@honeydrive:~/Desktop/shiva-installer$ 


By the way, we have tried this on Kali, Ununbut 12.4 Desktop, HoneyDrive, Debian and they all produce the same error.

I did have this working flawlessly week before last, just running the script worked fine.. Now it seems it always gets stuck at this point.

**Comment by zerokewl88** [comment]
Hi, i think i found a workaround.. after it gets to this error..

I go into shiva/shivaReceiver
source bin/activate
pip install docutils
pip install lamson

after that when i ran it, i was able to past this error and also did the same for the shivaAnalyzer..

not sure but will post more results tomorrow after successfully deployment, at the moment i deployed on 1 machine, but will reconfirm after testing on another machine.

thanks

**Comment by zerokewl88** [comment]
Sorry the above didn't work..

**Comment by tweemeterjop** [comment]
I struggled with this for some days aswell. The newer version of python-daemon seems to break the install. So installing an older version with the docutils dependency fixes the 'no module named version' issue. Add the following two lines before the 'pip install lamson' command in install.sh. This goes for the receiver and the analyzer.

    pip install docutils
    pip install python-daemon==2.0.2
    pip install lamson

**Comment by zerokewl88** [comment]
This fixes the issue - thank you for your help :)
